/**
 * Client List API\'s
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClientDto { 
    id?: number;
    /**
     * client\'s first name
     */
    firstName: string;
    lastName: string;
    postalCode: string;
    dateOfBirth: string;
}

