/**
 * Client List API\'s
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Link } from './link';


export interface EntityModelUserDto { 
    email: string;
    password: string;
    _links?: { [key: string]: Link; };
}

