/**
 * Client List API\'s
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntityModelClientDto } from './entityModelClientDto';


export interface PagedModelEntityModelClientDtoEmbedded { 
    clientDtoList?: Array<EntityModelClientDto>;
}

