/**
 * Client List API\'s
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetadata } from './pageMetadata';
import { PagedModelEntityModelClientDtoEmbedded } from './pagedModelEntityModelClientDtoEmbedded';
import { Link } from './link';


export interface PagedModelEntityModelClientDto { 
    _embedded?: PagedModelEntityModelClientDtoEmbedded;
    _links?: { [key: string]: Link; };
    page?: PageMetadata;
}

